import marimo

__generated_with = "0.16.5"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    # DC-TAP-seq CTCF Element Further Analysis Notebook

    > :warning: **DEPRECATED:** This notebook is mostly exploratory and
    > is not expected to run smoothly out of the box or be optimized for
    > readability and code quality . See
    > `analyses/2025-12-04/element-category-profile-analysis.py` for the
    > clean version of this notebook's core analysis.

    This notebook explores the significant WTC11 DE-G pairs where the assigned element 
    category is "CTCF Element".

    Questions:
    1. Do they (CTCF sites) show some low level of H3K27ac?
    2. Are the guides that exhibit the strongest effects at these
       elements very close to the CTCF binding site (motif)?
    """
    )
    return


@app.cell
def _():
    import os
    import re
    import sys
    import subprocess
    from pathlib import Path

    import math
    import numpy as np
    import pandas as pd

    import matplotlib.pyplot as plt

    from pybedtools import BedTool

    # Import custom scripts
    sys.path.insert(1, "src/python/") 
    import bedscripts as bs
    import singletonscripts as ss
    import commonscripts as cs
    return BedTool, Path, bs, cs, np, os, pd, subprocess


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Main Notebook

    See **Run Scripts & Functions** section for main notebook code execuation, analysis & results.
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ### File Dependencies:
    1. Processed DC-TAP-seq Paper Table S3. See `analysis/2025-11-14/target-selection-v2.py` to generate
       required files.

    2. WTC11 gRNA design file (this file is not generated by script above).

    To download WTC11 gRNA design file from DC-TAP-seq Analysis Pipeline Github.
    ```bash
    curl -L "https://raw.githubusercontent.com/EngreitzLab/DC_TAP_Paper/refs/tags/v1.0.0/resources/process_validation_datasets/WTC11_DC_TAP_Seq/220308_WTC11_Random_Screen_sgOpti-DC.design.txt" -o data/2025-11-14/dctapseq-randscreen-wtc11-grna-design.tsv
    ```

    **Important note about WTC11 gRNA design file above:**
    > There are 6 guide sequences that are duplicated, and thus have two named guides with the same sequence. 
    > Because the duplicates have the same target, this doesn't change the outcome of the screen
    > But, because the screen was run with each individual guide, these duplicates are not removed from the table.
    > 
    > The names with duplicated sequences:
    > 
    > WTC11_Random_Screen_Crop_14742 WTC11_Random_Screen_Crop_14743 
    > 
    > WTC11_Random_Screen_Crop_7289 WTC11_Random_Screen_Crop_ROCK1 
    > 
    > WTC11_Random_Screen_Crop_14744 WTC11_Random_Screen_Crop_14745 
    >
    > WTC11_Random_Screen_Crop_14746 WTC11_Random_Screen_Crop_14747 
    >
    > WTC11_Random_Screen_Crop_2422 WTC11_Random_Screen_Crop_BAG3 
    >
    > WTC11_Random_Screen_Crop_14748 WTC11_Random_Screen_Crop_14749 
    >
    > Two of these duplicate pairs are because 10 guides were added from the Jones group.


    ### Encode References
    ENCODE Project Data References:
    DNase
    - Experiment Dataset ID: ENCSR785ZUI
    - Lab: John Stamatoyannopoulos, UW
    - Date Released: May 19, 2021
    - Biosample: Homo sapiens WTC11
    - Assay: DNase-seq
    - Target: N/A
    - Nucleic acid type: DNA
    - Platform: Illumina HiSeq 4000
    - Accession Data File (DNase): ENCFF736FHB
    - Accession Data File (DHS): ENCFF525ZLI
    - Filetype: bigWig & bigBed

    H3K27ac
    - Experiment Dataset ID: ENCSR146DPQ
    - Lab: Bradley Bernstein, Broad
    - Date Released: September 27, 2021
    - Biosample: Homo sapiens WTC11
    - Assay: Mint-ChIP-seq
    - Target: H3K27ac
    - Nucleic acid type: DNA
    - Platform: Illumina NextSeq 500
    - Accession Data File: ENCFF306ZMK
    - Filetype: bigWig

    CTCF
    - Experiment Dataset ID: ENCSR992XTY
    - Lab: Bradley Bernstein, Broad
    - Date Released: June 9, 2022
    - Biosample: Homo sapiens WTC11
    - Assay: ChIP-seq (TF ChIP-seq)
    - Target: CTCF
    - Nucleic acid type: DNA
    - Platform: Illumina NextSeq 500
    - Accession Data File: ENCFF619QDY
    - Filetype: bigWig
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Constants""")
    return


@app.cell
def _():
    GRNA_EFF_BD = "results/2025-11-14/2025-11-25-dctapseq-validation-wtc11-grna-pam-eff.bed"
    GRNA_EFF_BG = "results/2025-11-14/2025-11-25-dctapseq-validation-wtc11-grna-pam-eff.bedGraph"
    GRNA_EFF_BW = "results/2025-11-14/2025-11-25-dctapseq-validation-wtc11-grna-pam-eff.bedWig"

    # TO DELETE LATER
    TEST_GRNA_EFF_BD = "results/2025-11-14/2025-11-25-dctapseq-validation-wtc11-grna-pam-eff-testing.bed"

    CTCF_BW = "data/encode/ENCFF619QDY.bigWig"
    K27AC_BW = "data/encode/ENCFF306ZMK.bigWig"
    DNASE_BW = "data/encode/ENCFF736FHB.bigWig"

    DNASE_BM = "data/encode/ENCFF492WXQ.bam"
    MACS3_DS = "results/2025-11-14/macs-dnase/dnase_summits.bed"
    DNASE_SIG_SUMMITS = "results/2025-11-14/2025-11-25-dctapseq-validation-wtc11-sig-dnase-summits.bed"

    CTCF_MOTIFS_BD = "data/wtc11/wtc11_ctcf_motifs.bed"
    CTCF_MOTIFS_BW = "data/wtc11/tmp_wtc11_ctcf-motif.bigwig"
    return (
        CTCF_BW,
        CTCF_MOTIFS_BW,
        DNASE_BM,
        DNASE_BW,
        GRNA_EFF_BD,
        K27AC_BW,
        MACS3_DS,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Load Data""")
    return


@app.cell
def _(pd):
    raw_tbl_s3_wtc11_significant = pd.read_csv(
        "results/2025-11-14/lowMOIvshighMOI-Validation-Experiment/" + 
        "2025-11-20-dctapseq-validation-wtc11-sig-egpairs-table-s3.tsv", 
        sep="\t",
        dtype={
            "significant_wo_pos_controls_20fdr": str
        }
    )

    raw_wtc11_grna_design = pd.read_csv(
        "data/2025-11-14/dctapseq-randscreen-wtc11-grna-design.tsv",
        sep="\t"
    )

    raw_wtc11_singleton = pd.read_csv(
        "data/2025-11-14/wtc11-singleton.tsv",
        sep="\t",
        dtype={
            "significant": "boolean"
        }
    )
    return (
        raw_tbl_s3_wtc11_significant,
        raw_wtc11_grna_design,
        raw_wtc11_singleton,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Pre-processing Data""")
    return


@app.cell
def _preprocess(
    BedTool,
    GRNA_EFF_BD,
    Path,
    bs,
    cs,
    final_out2,
    np,
    o1,
    pd,
    raw_tbl_s3_wtc11_significant,
    raw_wtc11_grna_design,
    raw_wtc11_singleton,
):
    def _preprocess_singleton_mkbed_pamcoords(df2, g1):
        """
        Method to get the PAM genomic coordinates (hg38) 
        of the gRNA after alignment
        """
        # I/O
        dir = "results/2025-11-14/ctcf-analysis-intermediates/"
        fastq_o = "results/2025-11-14/ctcf-analysis-intermediates/wtc-grna-pam.fastq"
        psl_o = "results/2025-11-14/ctcf-analysis-intermediates/wtc-grna-pam.psl"
        bed_o = "results/2025-11-14/ctcf-analysis-intermediates/wtc-grna-pam-fullseq.bed"
        cs.mkdir(dir)

        # Align gRNA sequence to reference genome using blat
        df_tmp = df2.copy().drop_duplicates(subset=[g1])
        bs.mkfastq_for_blat(df_tmp, o1, g1, fastq_o)
        bs.blat(fastq_o, psl_o)
        bs.convert_psl_to_bed(psl_o, bed_o)

        # Find the PAM coordinates based off strand
        fullseq = pd.read_csv(bed_o, sep="\t", header=None)
        fullseq[1] = np.where(fullseq[5] == "+", fullseq[2] - 3, fullseq[1])
        fullseq[2] = np.where(fullseq[5] == "+", fullseq[2], fullseq[1] + 3)

        # Write to Storage
        pam = BedTool.from_dataframe(fullseq)
        pam.saveas(final_out2)

    def _preprocess_singleton_merge_pamcoords(df2, pam, dict, key):
        """
        Helper method to merge singleton pamcoord columns to singleton df.
        """
        g1 = key
        df2 = df2.merge(
            pam[list(dict.values())],
            left_on=[g1],
            right_on=[g1],
            how="left"
        )
        return df2

    def _preprocess_singleton_expand_pamcoords(pam, offset, colname_dict, out):
        """
        Method to expand PAM genomic coordinates by an offset.
        """
        # Expand PAM genomic coords by offset using BedTools slop
        pam = BedTool.from_dataframe(pam).slop(genome="hg38", l=offset, r=offset).to_dataframe()

        # Offset coordinate window by +/-150-bp
        pam = _preprocess_singleton_expand_pamcoords(pam, offset)

        # Write to Results
        pam.saveas(out)

        ## Rename column header
        pam.columns = range(pam.shape[1])
        pam = pam.rename(columns=colname_dict)

        return pam

    def _preprocess_singleton():
        # Inputs
        df1 = raw_wtc11_grna_design.copy()
        df2 = raw_wtc11_singleton.copy()

        # GOAL 1: 
        # For each singleton gRNA, get the guide sequence with PAM from the design file
        m1 = "name"
        o1 = "GuideSequenceWithPAM"
        g1 = "grna_id"

        ## Rename ID to match Table S3 standards and obtain GuideSequenceWithPAM col
        df1[m1] = df1[m1].str.replace(
            "WTC11_Random_Screen_sgOpti-DC",
            "WTC11_Random_Screen_Crop",
            regex=False
        )
        df1 = df1.loc[:, [m1, o1]]
        df1 = df1.set_index(m1)

        ## Merge df1 and df2
        df2[o1] = df2[g1].map(df1[o1])


        # GOAL 2: 
        # Get the PAM genomic coordinates (hg38) of the gRNA after alignment
        final_out2 ="results/2025-11-14/2025-11-20-dctapseq-validation-wtc11-grna-pam.bed"
        if not cs.file_exist(final_out2):
            _preprocess_singleton_mkbed_pamcoords(df2, g1)

        # GOAL 3: 
        # Merge PAM genomic coordinates to singleton dataframe
        p3_dict = {
            0 : "pamcoords_chr",
            1 : "pamcoords_start",
            2 : "pamcoords_end",
            3 : g1,
            #4 : "score?",
            5 : "pamcoords_strand"
        }
        pam = pd.read_csv(final_out2, sep="\t", header=None).rename(columns=p3_dict)

        ## Merge columns using g1 = "grna_id"
        df2 = _preprocess_singleton_merge_pamcoords(df2, pam, p3_dict, key = g1)

        return df2

    def _preprocess_singleton_merge(df_s3, df_sing):
        """
        Helper Method to merge Singleton to Table S3 and format column names.
        """
        # Split comma-separated guide_ids into lists
        df_s3["guide_list"] = df_s3["guide_ids"].str.split(",")

        # Explode to one row per guid
        df_s3_expanded = df_s3.explode("guide_list")
        df_s3_expanded["guide_list"] = df_s3_expanded["guide_list"].str.strip()

        # Select singleton columns
        cols = [
            "grna_id",
            "pass_qc",
            "response_id",
            "pct_change_effect_size",
            "n_nonzero_trt",
            "n_nonzero_cntrl",
            "standard_error_pct_change",
            "GuideSequenceWithPAM"
        ]
        cols.extend([c for c in df_sing.columns if c.startswith("pamcoords")])

        # Merge with df_sing to get effect_size for each guide
        merged = df_s3_expanded.merge(
            df_sing[cols],
            left_on=["guide_list", "gene_id"],
            right_on=["grna_id", "response_id"],
            how="left",
        )

        # Re-label column names
        merged = merged.rename(
            columns={
                "pass_qc" : "singleton_pass_qc",
                "response_id": "singleton_response_id",
                "pct_change_effect_size_x": "pct_change_effect_size",  # fix original colname
                "pct_change_effect_size_y": "singleton_pct_change_effect_size",
                "n_nonzero_trt": "singleton_n_nonzero_trt",
                "n_nonzero_cntrl": "singleton_n_nonzero_cntrl",
                "standard_error_pct_change_x": "standard_error_pct_change",  # fix original colname
                "standard_error_pct_change_y": "singleton_standard_error_pct_change",
            }
        )

        return merged 

    def _preprocess_mkbed_grna_for_deeptools(dfi_sig_wtc11_grna):
        df = dfi_sig_wtc11_grna.copy()

        # Drop all singleton that did not pass SCEPTRE QC
        df = df[df["singleton_pass_qc"]]

        # Drop singleton that did not align and log
        df_dropout = df[df["pamcoords_chr"].isna()].to_csv(
            str(Path(GRNA_EFF_BD).parent) + "/" + 
            Path(GRNA_EFF_BD).stem + "-dropout.log",
            sep = "\t"
        )
        df = df[df["pamcoords_chr"].notna()]

        bed_df = pd.DataFrame(
            {
                "chr": df["pamcoords_chr"],
                "start": df["pamcoords_start"].astype(int),
                "end": df["pamcoords_end"].astype(int),
                "name": df["element_gene_pair_identifier_hg38"] + "|" + df["grna_id"],
                "score": df["singleton_pct_change_effect_size"] * -1.0,
                "strand": df["pamcoords_strand"],
                "thickStart": ".",
                "thickEnd": ".",
                "itemRgb": ".",
                "blockCount": ".",
                "blockSizes": ".",
                "blockStarts": ".",
                "pair_eff" : df["pct_change_effect_size"],            #13
                "grna_eff" : df["singleton_pct_change_effect_size"],  #14 
                "GuideSequenceWithPAM" : df["GuideSequenceWithPAM"],  #15
                "pair_id" : df["element_gene_pair_identifier_hg38"],  #16
                "grna_id" : df["grna_id"],                            #17
                "pair_elm_cat" : df["element_category"]               #18
            }
        )
        BedTool.from_dataframe(bed_df).saveas(GRNA_EFF_BD)

    def preprocess():
        dfi_singleton = _preprocess_singleton()
        dfi_sig_wtc11_grna = _preprocess_singleton_merge(raw_tbl_s3_wtc11_significant.copy(), dfi_singleton)

        _preprocess_mkbed_grna_for_deeptools(dfi_sig_wtc11_grna)

        # Filter for significant WTC11 E-G pairs whose element cateogry is "CTCF". (Expected_N = 14 DE-G pairs)
        df = dfi_sig_wtc11_grna
        #df = df[df["element_category"].str.contains("CTCF")].reset_index(drop=True)

        return df
    return (preprocess,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Functions & Methods""")
    return


@app.cell
def _(
    BedTool,
    CTCF_BW,
    DNASE_BM,
    DNASE_BW,
    K27AC_BW,
    MACS3_DS,
    Path,
    bs,
    cs,
    np,
    os,
    subprocess,
):
    def fetch_encode_data():
        bw_dict = {
            "ENCFF974CGC" : CTCF_BW, 
            "ENCFF573DHK" : K27AC_BW,
            "ENCFF736FHB" : DNASE_BW,
            "ENCFF492WXQ" : DNASE_BM
        }

        # Download bigWig ENCODE files
        for k, v in bw_dict.items():
            if cs.file_exist(v):
                continue
            subprocess.run([
                "curl", "-LO",
                "--output-dir", Path(v).parent,
                f"https://www.encodeproject.org/files/{k}/@@download/{v}"
            ])

    def fetch_chromsizes(g: str) -> str:
        f = f"data/refs/{g}.chrom.sizes"
        if not cs.file_exist(f):
            with open(f, "w") as out:
                subprocess.run(
                    ["fetchChromSizes", g],
                    stdout=out,
                    check=True
                )
        return f

    def make_grna_bigwig(bed: str,window: int, viewport: int = 1000) -> str:
        """
        Function to make a gRNA bigWig file where the signal is SCEPTRE analyzed 
        % Change Effect Size (PC) for deepTools usage compatibility.

        Parameters
        ----------
        bed : str filepath of grna bed file where the genomic coordinates (hg38) interval is a gRNA's PAM
        window : int that denotes the base-pair window to expand the gRNA PAM for averaging overlapping PC

        EXPECTED INPUT STRUCTURE
        ------------------------
        see method `_preprocess_mkbed_grna_for_deeptools()`.
        However, for this function to work, only `chr`, `start`, `end`, `name`, and `score` is required.
        The rest of the columns are optional.
        """
        dir = Path(bed).parent
        fbed = Path(Path(bed).stem)
        fbed_window = Path(f"{fbed}-{window}bp.bed")
        fbed_merged = Path(f"{fbed}-{window}bp-merged.bed")
        fbed_bp = Path(f"{fbed}-{window}bp-1bp-windows.bed")
        fbed_bg = Path(f"{fbed}-{window}bp.bedGraph")
        fbed_bw = Path(f"{fbed}-{window}bp.bigWig")

        # Expand intervals by window
        bed = (
            BedTool(bed)
                .slop(genome="hg38", l=window, r=window)
                .saveas(dir / fbed_window)
        )

        # Sort & overwrite file in-place
        tmp = fbed_window.with_suffix(fbed_window.suffix + ".tmp")
        with open(tmp, "w") as o:
            subprocess.run([
                "sort", "-k", "1,1", "-k2,2n", dir / fbed_window
            ], check=True, stdout=o)
        os.replace(tmp, dir / fbed_window)

        # Merge for minimal intervals to make 1bp interval
        bed = (
            BedTool(MACS3_DS)
                .slop(genome="hg38", l=viewport, r=viewport)
                .intersect(bed, wa=True)
                .merge().saveas(dir / fbed_merged)
        )

        # Make 1bp windows and assign gRNA effect
        bed = BedTool().makewindows(b=bed, w=1).saveas(dir / fbed_bp)

        # Map overlapping gRNA effect sizes and compute mean at 1-bp resolution
        bed = BedTool().map(a=bed, b=BedTool(dir / fbed_window), c=5, o="mean", null=0).saveas(dir / fbed_bg)

        # Fetch hg38 chromsizes
        chromsizes = fetch_chromsizes("hg38")

        # Convert bedGraph to bigWig
        subprocess.run([
            "bedGraphToBigWig", f"{dir / fbed_bg}", chromsizes, f"{dir / fbed_bw}"
        ])

        return str(dir / fbed_bw)
    
    def get_macs3_dnase_summits(name="dnase") -> str:
        if cs.file_exist(MACS3_DS):
            return MACS3_DS

        outdir = "results/2025-11-14/macs-dnase/"
        subprocess.run([
            "macs3", 
            "callpeak", 
            "-t", DNASE_BM, 
            "-f", "BAM",
            "-g", "hs", 
            "-n", name, 
            "-q", "0.1", 
            "--outdir", outdir
        ])

        return MACS3_DS

    def get_deeptools_references(df, outdir: str, genPerRegions: bool = True):
        df = df.copy()
        outdir = Path(outdir)
        query = bs.mkbed(df)
        summits = BedTool(MACS3_DS)

        # Intersect summits with query to generate reference point bed per regions interested for deeptools
        references = (
            summits.intersect(query, wa=True, wb=True)
                .to_dataframe(usecols=[0, 1, 2, 8], names=["chr", "start", "end", "name"])
                .drop_duplicates(subset=["name"])
        )
    
        # Create reference bed
        cs.mkdir(outdir)
        references_labels = list([])
        if genPerRegions:
            references_labels = references["name"].str.replace(r"[|:]", "-", regex=True).tolist()
            for i, v in enumerate(references_labels):
                v = outdir / f"{v}"
                BedTool.from_dataframe(references.iloc[[i]]).saveas(v)
                references_labels[i] = str(v)
        else:
            v = outdir / "aggregrate"
            BedTool.from_dataframe(references).saveas(v)
            references_labels.extend([v])
    
        return references_labels

    def deeptools_computeMatrix(b, R: list[str], S: list[str], o: str) -> str:
        out_r = f"{o}.regions.bed"
        b = str(b)
        cmd = ["computeMatrix", "reference-point"]
        cmd.extend([
            "-b", b, "-a", b,
            "-bs", "1",
            "--averageTypeBins", "mean",
            "--skipZeros",
            "--missingDataAsZero",
            "-o", o,
            "-R"
        ])
        for r in R:
            cmd.extend([r])

        cmd.extend(["-S"])
        for s in S:
            cmd.extend([s])

        cs.mkdir(Path(o).parent)
        subprocess.run(cmd)

        return o

    def deeptools_plotProfiles(
        m: str, 
        o: str,
        perGroup: bool = False,
        rename: list[str] = None,
        colors: list[str] = None,
        refPointLabel: str = None,
        plotTitle: str = "",
        yAxisLabel: str = "",
        nPlots: int = None,
        legendLocation: str = "best"
    ):
        cmd = ["plotProfile"]
        cmd.extend([
            "-m", m,
            "-o", o,
            "--legendLocation", legendLocation,
            "--plotTitle", plotTitle,
            "--yAxisLabel", yAxisLabel
        ])

        if perGroup:
            cmd.extend(["--perGroup"])

        if rename is not None:
            cmd.extend(["--samplesLabel"])
            cmd.extend([n for n in rename])

        if colors is not None:
            cmd.extend(["--colors"])
            cmd.extend([c for c in colors])

        if refPointLabel is not None:
            cmd.extend(["--refPointLabel", refPointLabel])
        
        if nPlots is not None:
            n_display_rows = np.floor(np.sqrt(nPlots)).astype(int)
            cmd.extend(["--numPlotsPerRow", str(n_display_rows)])

        cs.mkdir(Path(o).parent)
        subprocess.run(cmd)
    return (
        deeptools_computeMatrix,
        deeptools_plotProfiles,
        fetch_chromsizes,
        get_deeptools_references,
        get_macs3_dnase_summits,
        make_grna_bigwig,
    )


@app.cell
def _(Path, cs, fetch_chromsizes, subprocess):
    def min_max_normalize_bedgraph(in_path: Path, out_path: Path) -> None:
        vmin = float("inf")
        vmax = float("-inf")

        # First pass: find min and max
        with in_path.open() as f:
            for line in f:
                if not line.strip():
                    continue
                fields = line.rstrip("\n").split("\t")
                val = float(fields[3])
                if val < vmin:
                    vmin = val
                if val > vmax:
                    vmax = val

        if vmax == vmin:
            # Avoid divide-by-zero; treat everything as 0 or 1 as you prefer
            scale = 1.0
        else:
            scale = vmax - vmin

        # Second pass: write normalized values
        with in_path.open() as fin, out_path.open("w") as fout:
            for line in fin:
                if not line.strip():
                    continue
                fields = line.rstrip("\n").split("\t")
                val = float(fields[3])
                norm = (val - vmin) / scale
                fields[3] = f"{norm:.6f}"
                fout.write("\t".join(fields) + "\n")

    def normalize_bigwig(inputs: list[str], method: str, outdir: str) -> list[str]:
        """
        naive method expected to take >1hr to run.

        note the dnase track has some non standard chr labels
        e.g. chrEBV etc. this breaks convert bedgraph to bigwig
        b/c hg38.chrom.sizes does not have those annotations
        """
        # methods = {
        #     "min-max" : min_max_normalize
        # }

        tmp_dir = Path(outdir) / "tmp-norm-bigwig"
        cs.mkdir(tmp_dir)

        chrom_sizes = fetch_chromsizes("hg38")

        # Convert to BedGraph
        # for bw in inputs:
        #     cmd = ["bigWigToBedGraph", bw, f"{tmp_dir / Path(bw).stem}.bedGraph"]
        #     subprocess.run(cmd)

        out_bws: list[str] = []
        done = tmp_dir / "normalized.DONE"

        if cs.file_exist(done):
            outs = list(tmp_dir.glob("*.bigWig"))
            outs = [str(o) for o in outs]
            return outs

        for bw in inputs:
            bw_path = Path(bw)
            stem = bw_path.stem

            # 1) bigWig -> bedGraph
            bedgraph = tmp_dir / f"{stem}.bedGraph"
            # cmd = ["bigWigToBedGraph", str(bw_path), str(bedgraph)]
            # subprocess.run(cmd, check=True)

            # 2) min–max normalize bedGraph
            norm_bedgraph = tmp_dir / f"{stem}.minmax.norm.bedGraph"
            min_max_normalize_bedgraph(bedgraph, norm_bedgraph)

            # 3) bedGraph -> bigWig
            out_bw = tmp_dir / f"{stem}.minmax.norm.bigWig"
            cmd = ["bedGraphToBigWig", str(norm_bedgraph), chrom_sizes, str(out_bw)]
            subprocess.run(cmd, check=True)

            out_bws.append(str(out_bw))

        done.touch()
        return out_bws
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Processing Data""")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Custom functions to perform one-off tasks on Fully Processed Data""")
    return


@app.cell(disabled=True)
def _(BedTool, Path, mo, os, pd, preprocess, subprocess):
    def make_singleton_bedgraph(df, o):
        o = Path(o)
        odir = o.parent
        fo_bed = Path(o.stem + ".bedGraph")
    
        bed = pd.DataFrame(
            {
                "chr": df.loc[:, "targeting_chr_hg38"],
                "start": df.loc[:, "pamcoords_start"],
                "end": df.loc[:, "pamcoords_end"],
                "score": df.loc[:, "singleton_pct_change_effect_size"],
            }
        )
    
        bed = BedTool.from_dataframe(bed).saveas(odir / fo_bed)
        tmp = fo_bed.with_suffix(fo_bed.suffix + ".tmp")
        with open(tmp, "w") as o:
            subprocess.run([
                "sort", "-k", "1,1", "-k2,2n", odir / fo_bed
            ], check=True, stdout=o)
        os.replace(tmp, odir / fo_bed)
    

    dfi_all_singleton_oneoff = preprocess()
    make_singleton_bedgraph(
        dfi_all_singleton_oneoff, 
        o="results/2025-11-14/2025-11-26-dctapseq-wtc11-sig-grna-pam-pct-eff-size.bedGraph"
    )
    mo.ui.dataframe(dfi_all_singleton_oneoff)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Run Scripts & Functions""")
    return


@app.cell
def _(preprocess):
    dfi = preprocess()
    dfi_ctcf = dfi.copy()[dfi["element_category"].str.contains("CTCF")].reset_index(drop=True)
    dfi_ctcf = dfi_ctcf[dfi_ctcf["pct_change_effect_size"] < 0].reset_index(drop=True)
    # fetch_encode_data()
    return dfi, dfi_ctcf


@app.cell
def _(dfi):
    dfi_h3k27ac = dfi.copy()[dfi["element_category"].eq("H3K27ac")].reset_index(drop=True)
    return


@app.cell
def _(BedTool, fetch_chromsizes, pd, subprocess):
    # Add WTC11 CTCF Motif bigwig track
    def make_ctcf_motif_bigwig(bed):
        fout_bedgraph = "results/2025-11-14/ctcf-analysis-plots/2025-12-04-crispri-meeting-manual/tmp/ctcf-motif.bedGraph"
        fout_bigwig = "results/2025-11-14/ctcf-analysis-plots/2025-12-04-crispri-meeting-manual/tmp/ctcf-motif.bigwig"
    
        bed = pd.read_csv(bed, sep="\t", header=None).loc[:, [0, 1, 2, 4]]
        bed = BedTool.from_dataframe(bed).merge(c=4, o="max").saveas(fout_bedgraph)
        chromsizes = fetch_chromsizes("hg38")
        subprocess.run([
            "bedGraphToBigWig", f"{fout_bedgraph}", chromsizes, f"{fout_bigwig}"
        ])

    # make_ctcf_motif_bigwig(CTCF_MOTIFS_BD)
    return


@app.cell
def _(GRNA_EFF_BD, get_macs3_dnase_summits, make_grna_bigwig):
    dt_grnaeff_150bp =  make_grna_bigwig(GRNA_EFF_BD, 150)
    dt_grnaeff_250bp =  make_grna_bigwig(GRNA_EFF_BD, 25)
    get_macs3_dnase_summits()
    return dt_grnaeff_150bp, dt_grnaeff_250bp


@app.cell
def _(dfi_ctcf, get_deeptools_references):
    dt_references_ctcf_elements_outdir = "results/2025-11-14/dt-intermediates/refs_ctcf_elements/"
    dt_references_ctcf_elements = get_deeptools_references(
        dfi_ctcf,
        outdir=dt_references_ctcf_elements_outdir,
    )
    dt_references_ctcf_elements_agg = get_deeptools_references(
        dfi_ctcf,
        outdir=dt_references_ctcf_elements_outdir,
        genPerRegions=False
    )
    return dt_references_ctcf_elements, dt_references_ctcf_elements_agg


@app.cell
def _():
    # minmax_normalized_bigwigs = normalize_bigwig(
    #     inputs = [CTCF_BW, K27AC_BW, DNASE_BW],
    #     method = "max-min",
    #     outdir = "results/2025-11-14/dt-intermediates/"
    # )
    return


@app.cell
def _(
    CTCF_BW,
    CTCF_MOTIFS_BW,
    DNASE_BW,
    K27AC_BW,
    deeptools_computeMatrix,
    dt_grnaeff_150bp,
    dt_grnaeff_250bp,
    dt_references_ctcf_elements,
    dt_references_ctcf_elements_agg,
):
    dt_mtx_150bp = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-150bp"
    m1 = deeptools_computeMatrix(
        b=1000, 
        R=dt_references_ctcf_elements, 
        S=[dt_grnaeff_150bp, dt_grnaeff_250bp, CTCF_BW, K27AC_BW, DNASE_BW], 
        o=dt_mtx_150bp + ".gz",
    )

    # dt_mtx_minmaxnorm_150bp = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-150bp.minmax.norm"
    # minmax_norm_150 = [dt_grnaeff_150bp]
    # minmax_norm_150.extend(minmax_normalized_bigwigs)
    # m2 = deeptools_computeMatrix(
    #     b=1000, 
    #     R=dt_references_ctcf_elements, 
    #     S=minmax_norm_150, 
    #     o=dt_mtx_minmaxnorm_150bp + ".gz",
    # )
    # 
    # dt_mtx_minmaxnorm_150n250bp = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-150bp-250bp.minmax.norm"
    # minmax_norm_150n250 = [dt_grnaeff_150bp, dt_grnaeff_250bp]
    # minmax_norm_150n250.extend(minmax_normalized_bigwigs)
    # m3 = deeptools_computeMatrix(
    #     b=1000, 
    #     R=dt_references_ctcf_elements, 
    #     S=minmax_norm_150n250, 
    #     o=dt_mtx_minmaxnorm_150n250bp + ".gz",
    # )
    # 
    # 
    # dt_mtx_minmaxnorm_150n250bp_agg = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-150bp-250bp.minmax.norm.agg"
    # m4 = deeptools_computeMatrix(
    #     b=1000, 
    #     R=dt_references_ctcf_elements_agg, 
    #     S=minmax_norm_150n250, 
    #     o=dt_mtx_minmaxnorm_150n250bp_agg + ".gz",
    # )
    # 
    # 
    dt_mtx_150n250bp_agg = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-150bp-250bp.agg"
    m4_4 = deeptools_computeMatrix(
        b=1000, 
        R=dt_references_ctcf_elements_agg, 
        S=[dt_grnaeff_150bp, dt_grnaeff_250bp, CTCF_BW, K27AC_BW, DNASE_BW, CTCF_MOTIFS_BW], 
        o=dt_mtx_150n250bp_agg + ".gz",
    )

    return m1, m4_4


@app.cell
def _(deeptools_plotProfiles, dt_references_ctcf_elements, m1, m4_4):
    p_dir = "results/2025-11-14/ctcf-analysis-plots/"
    deeptools_plotProfiles(
        m1, 
        o=p_dir + "grna-eff-vs-dhs-summit-mtx-150bp.png",
        perGroup=True,
        rename=["sgRNA-effect (150bp)", "sgRNA-effect (25bp)", "CTCF","H3K27ac", "DNase"],
        colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba"],
        refPointLabel="DHS Summit",
        yAxisLabel="Normalized Signal",
        nPlots=len(dt_references_ctcf_elements)
    )

    deeptools_plotProfiles(
        m4_4, 
        o=p_dir + "grna-eff-vs-dhs-summit-mtx-150bp-250bp.agg.png",
        perGroup=True,
        rename=["sgRNA-effect (150bp)", "sgRNA-effect (25bp)", "CTCF", "H3K27ac", "DNase", "CTCF Motifs"],
        colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba", "#4F7B7D"],
        refPointLabel="DHS Summit",
        yAxisLabel="Normalized Signal",
        nPlots=len(dt_references_ctcf_elements)
    )
    # 
    # deeptools_plotProfiles(
    #     m2, 
    #     o=p_dir + "grna-eff-vs-dhs-summit-mtx-150bp.minmax.norm.png",
    #     perGroup=True,
    #     rename=["sgRNA-effect", "CTCF", "H3K27ac", "DNase"],
    #     colors=["#f70707", "#71b0b3", "#e69533", "#4b79ba"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Min-Max Normalized Signal",
    #     nPlots=len(dt_references_ctcf_elements)
    # )
    # 
    # deeptools_plotProfiles(
    #     m3, 
    #     o=p_dir + "grna-eff-vs-dhs-summit-mtx-150bp-250bp.minmax.norm.png",
    #     perGroup=True,
    #     rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "CTCF", "H3K27ac", "DNase"],
    #     colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Min-Max Normalized Signal",
    #     nPlots=len(dt_references_ctcf_elements)
    # )
    return


@app.cell
def _():
    # Aggreated plots
    # deeptools_plotProfiles(
    #     m4, 
    #     o=p_dir + "grna-eff-vs-dhs-summit-mtx-150bp.minmax.norm.agg.png",
    #     rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "CTCF", "H3K27ac", "DNase"],
    #     colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Min-Max Normalized Signal",
    #     nPlots=len(dt_references_ctcf_elements),
    # )
    return


@app.cell
def _():
    # all elements
    # dt_references_all_elements_outdir = "results/2025-11-14/dt-intermediates/refs_all_elements/"
    # dt_references_all_elements = get_deeptools_references(
    #     dfi,
    #     outdir=dt_references_all_elements_outdir,
    # )
    # dt_references_all_elements_agg = get_deeptools_references(
    #     dfi,
    #     outdir=dt_references_all_elements_outdir,
    #     genPerRegions=False
    # )
    # 
    # 
    # dt_mtx_minmaxnorm_all_150n250bp = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-allpairs-150bp-250bp.minmax.norm"
    # m5 = deeptools_computeMatrix(
    #     b=1000, 
    #     R=dt_references_all_elements,
    #     S=minmax_norm_150n250, 
    #     o=dt_mtx_minmaxnorm_all_150n250bp + ".gz",
    # )
    # dt_mtx_minmaxnorm_all_150n250bp_agg = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-allpairs-150bp-250bp.minmax.norm.agg"
    # m6 = deeptools_computeMatrix(
    #     b=1000, 
    #     R=dt_references_all_elements_agg, 
    #     S=minmax_norm_150n250, 
    #     o=dt_mtx_minmaxnorm_all_150n250bp_agg + ".gz",
    # )
    # 
    # deeptools_plotProfiles(
    #     m5, 
    #     o=p_dir + "grna-eff-vs-dhs-summit-mtx-all-150bp-250bp.minmax.norm.png",
    #     perGroup=True,
    #     rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "CTCF", "H3K27ac", "DNase"],
    #     colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Min-Max Normalized Signal",
    #     nPlots=len(dt_references_all_elements)
    # )
    # deeptools_plotProfiles(
    #     m6, 
    #     o=p_dir + "grna-eff-vs-dhs-summit-mtx-all-150bp-250bp.minmax.norm.agg.png",
    #     rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "CTCF", "H3K27ac", "DNase"],
    #     colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Min-Max Normalized Signal"
    # )
    return


@app.cell
def _():
    # h3k27ac elements
    # dt_references_h3k27ac_elements_outdir = "results/2025-11-14/dt-intermediates/refs_h3k27ac_elements/"
    # dt_references_h3k27ac_elements = get_deeptools_references(
    #     dfi_h3k27ac,
    #     outdir=dt_references_h3k27ac_elements_outdir,
    # )
    # dt_references_h3k27ac_elements_agg = get_deeptools_references(
    #     dfi_h3k27ac,
    #     outdir=dt_references_h3k27ac_elements_outdir,
    #     genPerRegions=False
    # )
    # 
    # dt_mtx_minmaxnorm_h3k27ac_150n250bp = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-h3k27acpairs-150bp-250bp.minmax.norm"
    # m7 = deeptools_computeMatrix(
    #     b=1000, 
    #     R=dt_references_h3k27ac_elements,
    #     S=minmax_norm_150n250, 
    #     o=dt_mtx_minmaxnorm_h3k27ac_150n250bp + ".gz",
    # )
    # dt_mtx_minmaxnorm_h3k27ac_150n250bp_agg = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-h3k27acpairs-150bp-250bp.minmax.norm.agg"
    # m8 = deeptools_computeMatrix(
    #     b=1000, 
    #     R=dt_references_h3k27ac_elements_agg, 
    #     S=minmax_norm_150n250, 
    #     o=dt_mtx_minmaxnorm_h3k27ac_150n250bp_agg + ".gz",
    # )
    # 
    # 
    # dt_mtx_raw_h3k27ac_150n250bp = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-h3k27acpairs-150bp-250bp.raw"
    # m9 = deeptools_computeMatrix(
    #     b=1000, 
    #     R=dt_references_h3k27ac_elements,
    #     S=[dt_grnaeff_150bp, dt_grnaeff_250bp, CTCF_BW, K27AC_BW, DNASE_BW], 
    #     o=dt_mtx_raw_h3k27ac_150n250bp + ".gz",
    # )
    # dt_mtx_raw_h3k27ac_150n250bp_agg = "results/2025-11-14/dt-intermediates/grna-eff-vs-dhs-summit-mtx-h3k27acpairs-150bp-250bp.raw.agg"
    # m10 = deeptools_computeMatrix(
    #     b=1000, 
    #     R=dt_references_h3k27ac_elements_agg, 
    #     S=[dt_grnaeff_150bp, dt_grnaeff_250bp, CTCF_BW, K27AC_BW, DNASE_BW], 
    #     o=dt_mtx_raw_h3k27ac_150n250bp_agg + ".gz",
    # )
    # 
    # deeptools_plotProfiles(
    #     m7, 
    #     o=p_dir + "grna-eff-vs-dhs-summit-mtx-h3k27ac-150bp-250bp.minmax.norm.png",
    #     perGroup=True,
    #     rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "CTCF", "H3K27ac", "DNase"],
    #     colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Min-Max Normalized Signal",
    #     nPlots=len(dt_references_h3k27ac_elements)
    # )
    # deeptools_plotProfiles(
    #     m8, 
    #     o=p_dir + "grna-eff-vs-dhs-summit-mtx-h3k27ac-150bp-250bp.minmax.norm.agg.png",
    #     rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "CTCF", "H3K27ac", "DNase"],
    #     colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Min-Max Normalized Signal"
    # )
    # 
    # deeptools_plotProfiles(
    #     m9, 
    #     o=p_dir + "grna-eff-vs-dhs-summit-mtx-h3k27ac-150bp-250bp.raw.png",
    #     perGroup=True,
    #     rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "CTCF", "H3K27ac", "DNase"],
    #     colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Raw Signal",
    #     nPlots=len(dt_references_h3k27ac_elements)
    # )
    # deeptools_plotProfiles(
    #     m10, 
    #     o=p_dir + "grna-eff-vs-dhs-summit-mtx-h3k27ac-150bp-250bp.raw.agg.png",
    #     rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "CTCF", "H3K27ac", "DNase"],
    #     colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Raw Signal"
    # )
    return


@app.cell
def _(
    DNASE_BW,
    K27AC_BW,
    deeptools_computeMatrix,
    deeptools_plotProfiles,
    dt_grnaeff_150bp,
    dt_grnaeff_250bp,
    dt_references_h3k27ac_elements,
    dt_references_h3k27ac_elements_agg,
    minmax_normalized_bigwigs,
):
    def _():
        # h3k27ac elements no CTCF track

        p_dir = "results/2025-11-14/ctcf-analysis-plots/no-ctcf/"
        minmax_norm_150n250 = [dt_grnaeff_150bp, dt_grnaeff_250bp]
        minmax_norm_150n250.extend(minmax_normalized_bigwigs)
        minmax_norm_150n250.remove("results/2025-11-14/dt-intermediates/tmp-norm-bigwig/ENCFF974CGC.minmax.norm.bigWig")
        dt_mtx_minmaxnorm_h3k27ac_150n250bp = "results/2025-11-14/dt-intermediates/no-ctcf/grna-eff-vs-dhs-summit-mtx-h3k27acpairs-150bp-250bp.minmax.norm"
        m11 = deeptools_computeMatrix(
            b=1000, 
            R=dt_references_h3k27ac_elements,
            S=minmax_norm_150n250, 
            o=dt_mtx_minmaxnorm_h3k27ac_150n250bp + ".gz",
        )
        dt_mtx_minmaxnorm_h3k27ac_150n250bp_agg = "results/2025-11-14/dt-intermediates/no-ctcf/grna-eff-vs-dhs-summit-mtx-h3k27acpairs-150bp-250bp.minmax.norm.agg"
        m12 = deeptools_computeMatrix(
            b=1000, 
            R=dt_references_h3k27ac_elements_agg, 
            S=minmax_norm_150n250, 
            o=dt_mtx_minmaxnorm_h3k27ac_150n250bp_agg + ".gz",
        )


        dt_mtx_raw_h3k27ac_150n250bp = "results/2025-11-14/dt-intermediates/no-ctcf/grna-eff-vs-dhs-summit-mtx-h3k27acpairs-150bp-250bp.raw"
        m13 = deeptools_computeMatrix(
            b=1000, 
            R=dt_references_h3k27ac_elements,
            S=[dt_grnaeff_150bp, dt_grnaeff_250bp, K27AC_BW, DNASE_BW], 
            o=dt_mtx_raw_h3k27ac_150n250bp + ".gz",
        )
        dt_mtx_raw_h3k27ac_150n250bp_agg = "results/2025-11-14/dt-intermediates/no-ctcf/grna-eff-vs-dhs-summit-mtx-h3k27acpairs-150bp-250bp.raw.agg"
        m14 = deeptools_computeMatrix(
            b=1000, 
            R=dt_references_h3k27ac_elements_agg, 
            S=[dt_grnaeff_150bp, dt_grnaeff_250bp, K27AC_BW, DNASE_BW], 
            o=dt_mtx_raw_h3k27ac_150n250bp_agg + ".gz",
        )

        deeptools_plotProfiles(
            m11, 
            o=p_dir + "grna-eff-vs-dhs-summit-mtx-h3k27ac-150bp-250bp.minmax.norm.png",
            perGroup=True,
            rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "H3K27ac", "DNase"],
            colors=["#f70707", "#c60606", "#e69533", "#4b79ba"],
            refPointLabel="DHS Summit",
            yAxisLabel="Min-Max Normalized Signal",
            nPlots=len(dt_references_h3k27ac_elements)
        )
        deeptools_plotProfiles(
            m12, 
            o=p_dir + "grna-eff-vs-dhs-summit-mtx-h3k27ac-150bp-250bp.minmax.norm.agg.png",
            rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "H3K27ac", "DNase"],
            colors=["#f70707", "#c60606", "#e69533", "#4b79ba"],
            refPointLabel="DHS Summit",
            yAxisLabel="Min-Max Normalized Signal"
        )

        deeptools_plotProfiles(
            m13, 
            o=p_dir + "grna-eff-vs-dhs-summit-mtx-h3k27ac-150bp-250bp.raw.png",
            perGroup=True,
            rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "H3K27ac", "DNase"],
            colors=["#f70707", "#c60606", "#e69533", "#4b79ba"],
            refPointLabel="DHS Summit",
            yAxisLabel="Raw Signal",
            nPlots=len(dt_references_h3k27ac_elements)
        )
        return deeptools_plotProfiles(
            m14, 
            o=p_dir + "grna-eff-vs-dhs-summit-mtx-h3k27ac-150bp-250bp.raw.agg.png",
            rename=["sgRNA-effect (150bp)", "sgRNA-effect (250bp)", "H3K27ac", "DNase"],
            colors=["#f70707", "#c60606", "#e69533", "#4b79ba"],
            refPointLabel="DHS Summit",
            yAxisLabel="Raw Signal"
        )


    # _()
    return


@app.cell
def _(Path, cs, np, subprocess):
    def deeptools_plotHeatmap(
        m: str, 
        o: str,
        perGroup: bool = False,
        rename: list[str] = None,
        colors: list[str] = None,
        refPointLabel: str = None,
        plotTitle: str = "",
        yAxisLabel: str = "",
        nPlots: int = None,
        legendLocation: str = "best"
    ):
        cmd = ["plotHeatmap"]
        cmd.extend([
            "-m", m,
            "-o", o,
            "--legendLocation", legendLocation,
            "--plotTitle", plotTitle,
            "--yAxisLabel", yAxisLabel,
            "--colorMap", "Reds"
        ])

        if perGroup:
            cmd.extend(["--perGroup"])

        if rename is not None:
            cmd.extend(["--samplesLabel"])
            cmd.extend([n for n in rename])

        if colors is not None:
            cmd.extend(["--colors"])
            cmd.extend([c for c in colors])

        if refPointLabel is not None:
            cmd.extend(["--refPointLabel", refPointLabel])
        
        if nPlots is not None:
            n_display_rows = np.floor(np.sqrt(nPlots)).astype(int)
            cmd.extend(["--numPlotsPerRow", str(n_display_rows)])

        cs.mkdir(Path(o).parent)
        subprocess.run(cmd)
    return (deeptools_plotHeatmap,)


@app.cell
def _(deeptools_plotHeatmap, m4_4):
    p_hdir = "results/2025-11-14/ctcf-analysis-plots/heatmaps/"
    # deeptools_plotHeatmap(
    #     m1, 
    #     o=p_hdir + "grna-eff-vs-dhs-summit-mtx-150bp.png",
    #     perGroup=True,
    #     rename=["sgRNA-effect", "CTCF", "H3K27ac", "DNase"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Raw Signal",
    # )

    # deeptools_plotHeatmap(
    #     m2, 
    #     o=p_hdir + "grna-eff-vs-dhs-summit-mtx-150bp.minmax.norm.svg",
    #     perGroup=True,
    #     rename=["sgRNA-effect", "CTCF", "H3K27ac", "DNase"],
    #     refPointLabel="DHS Summit",
    #     yAxisLabel="Min-Max Normalized Signal",
    # )

    deeptools_plotHeatmap(
        m4_4, 
        o=p_hdir + "grna-eff-vs-dhs-summit-mtx-150bp-250bp.agg.png",
        rename=["sgRNA-effect (150bp)", "sgRNA-effect (25bp)", "CTCF", "H3K27ac", "DNase", "CTCF Motifs"],
        refPointLabel="DHS Summit",
        yAxisLabel="Normalized Signal",
    )
    return


@app.cell
def _(dt_grnaeff_250bp, dt_references_ctcf_elements_agg):
    print(dt_grnaeff_250bp)
    print(dt_references_ctcf_elements_agg)
    return


@app.cell
def _(
    CTCF_BW,
    CTCF_MOTIFS_BW,
    DNASE_BW,
    GRNA_EFF_BD,
    K27AC_BW,
    deeptools_computeMatrix,
    deeptools_plotHeatmap,
    deeptools_plotProfiles,
    dt_grnaeff_150bp,
    dt_grnaeff_250bp,
    dt_references_ctcf_elements,
    dt_references_ctcf_elements_agg,
    make_grna_bigwig,
):
    # Get a zoomed in looked (+/-200bp)
    dt_grnaeff_150bp_200vp =  make_grna_bigwig(GRNA_EFF_BD, 150, viewport=500)
    dt_grnaeff_250bp_200vp =  make_grna_bigwig(GRNA_EFF_BD, 25, viewport=500)

    dt_mtx_150bp_200vp = "results/2025-11-14/dt-intermediates/tmp-200vp-zoomed/grna-eff-vs-dhs-summit-mtx-150bp"
    m1_200vp = deeptools_computeMatrix(
        b=500, 
        R=dt_references_ctcf_elements, 
        S=[dt_grnaeff_150bp, dt_grnaeff_250bp, CTCF_BW, K27AC_BW, DNASE_BW], 
        o=dt_mtx_150bp_200vp + ".gz",
    )

    dt_mtx_150n250bp_agg_200vp = "results/2025-11-14/dt-intermediates/tmp-200vp-zoomed/grna-eff-vs-dhs-summit-mtx-150bp-250bp.agg"
    m4_4_200vp = deeptools_computeMatrix(
        b=500, 
        R=dt_references_ctcf_elements_agg, 
        S=[dt_grnaeff_150bp, dt_grnaeff_250bp, CTCF_BW, K27AC_BW, DNASE_BW, CTCF_MOTIFS_BW], 
        o=dt_mtx_150n250bp_agg_200vp + ".gz",
    )

    p_dir_200vp = "results/2025-11-14/ctcf-analysis-plots/tmp-200vp/"
    deeptools_plotProfiles(
        m1_200vp, 
        o=p_dir_200vp + "grna-eff-vs-dhs-summit-mtx-150bp.svg",
        perGroup=True,
        rename=["sgRNA-effect (150bp)", "sgRNA-effect (25bp)", "CTCF","H3K27ac", "DNase"],
        colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba"],
        refPointLabel="DHS Summit",
        yAxisLabel="Normalized Signal",
        nPlots=len(dt_references_ctcf_elements)
    )

    deeptools_plotProfiles(
        m4_4_200vp, 
        o=p_dir_200vp + "grna-eff-vs-dhs-summit-mtx-150bp-250bp.agg.svg",
        perGroup=True,
        rename=["sgRNA-effect (150bp)", "sgRNA-effect (25bp)", "CTCF", "H3K27ac", "DNase", "CTCF Motifs"],
        colors=["#f70707", "#c60606", "#71b0b3", "#e69533", "#4b79ba", "#4F7B7D"],
        refPointLabel="DHS Summit",
        yAxisLabel="Normalized Signal",
        nPlots=len(dt_references_ctcf_elements)
    )
    p_hdir_200vp = "results/2025-11-14/ctcf-analysis-plots/tmp-200vp/heatmaps/"
    deeptools_plotHeatmap(
        m4_4_200vp, 
        o=p_hdir_200vp+ "grna-eff-vs-dhs-summit-mtx-150bp-250bp.agg.svg",
        rename=["sgRNA-effect (150bp)", "sgRNA-effect (25bp)", "CTCF", "H3K27ac", "DNase", "CTCF Motifs"],
        refPointLabel="DHS Summit",
        yAxisLabel="Normalized Signal",
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Exploration""")
    return


@app.cell
def _(dfi_ctcf, mo):
    def _():
        """
        List unique sig CTCF sites from screen. Should be 14 pairs in total.
        """
        m1 = "element_gene_pair_identifier_hg38"
        m2 = "pct_change_effect_size"
        df = dfi_ctcf.copy().loc[:, [m1, m2]].drop_duplicates(subset=[m1, m2]).reset_index(drop=True)
        return df
    mo.ui.table(_())
    return


@app.cell
def _(dfi, mo):
    mo.ui.table(dfi["element_category"].unique().tolist())
    return


@app.cell
def _(dfi_ctcf, mo):
    # CTCF Test 1 - Only looking at FAM111A|chr11:59158502-59158803
    dir1 = "results/2025-11-14/per-grna-ctcf-plots/test1/"

    df1 = dfi_ctcf.copy()
    df1 = df1[df1["element_gene_pair_identifier_hg38"].eq("RPL8|chr8:144479012-144479313")]
    mo.ui.dataframe(df1)

    # recreate bedgraph
    # create a bed with grna with no signal
    # if time, create a bedgraph track per grna with umi colored by sceptre out put single (pct change effect)
    return


if __name__ == "__main__":
    app.run()
