import marimo

__generated_with = "0.16.5"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    # DC-TAP-seq Validation Target Selection Notebook v2

    This notebook explores the metadata from DC-TAP-seq manuscript Table S3 to appropriately select targets.
    """
    )
    return


@app.cell
def _():
    import re
    import subprocess
    from pathlib import Path

    import math
    import numpy as np
    import pandas as pd

    import matplotlib.pyplot as plt

    from pybedtools import BedTool
    return BedTool, Path, pd, subprocess


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Main Notebook""")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ### Download data

    Required Files:
    1. DC-TAP-seq Paper Table S3
    2. WTC11 Singleton Analysis Result TSV

    Download Table S3 from [DC-TAP-seq Paper Preprint Supplementary](https://doi.org/10.1101/2025.09.16.676677). 
    Or for convenience, use the `CMD` snippet below at `validation` root directory to download Table S3 from 
    [github](https://github.com/EngreitzLab/DC_TAP_Paper/blob/v1.0.0).

    ```bash
    mkdir -p data/2025-11-14/
    curl -L "https://raw.githubusercontent.com/EngreitzLab/DC_TAP_Paper/refs/tags/v1.0.0/results/formatted_dc_tap_results/Table_S3_Final_DC_TAP_Seq_Results_w_Chromatin_Categories_on_resized_and_merged_elements_250908_append.tsv" -o data/2025-11-14/dctapseq-tables3-wtc11.tsv
    ```

    To download the WTC11 sceptre singleton results.

    ```bash
    curl "https://mitra.stanford.edu/engreitz/oak/public/RayJagoda2024/DC-TAPseq/validations/WTC11/resources/2025-08-10-dctapseq-sceptre-wtc11-singleton.tsv" -o data/2025-11-14/wtc11-singleton.tsv
    ```

    To download the GENCODE v44 GTF. Version 44 was used to match the GENCODE references used in the 
    10X software for pre-processing of the sequencing raw data.

    ```bash
    mkdir -p data/2025-11-14/standardized
    curl -L "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.annotation.gtf.gz" -o data/2025-11-14/standardized/gencode.v44.annotation.gtf.gz
    ```

    To download the 2022-06-25 TF-Perturb-seq WTC11 & CIRM Village Hepatic Neuronal TPM/CPM dataset
    generated by Jones Group from the Lander Lab at the Broad Institute.

    ```bash
    mkdir -p data/2025-11-14/2022-06-25-wtc11-tfperturbseq-ref
    curl "https://mitra.stanford.edu/engreitz/oak/public/RayJagoda2024/DC-TAPseq/validations/WTC11/resources/2022-06-25-wtc11-tfperturbseq-ref/CIRM_villages_hepatic_neuronal_120121_TPM_tables_WTC11_avg_geneTPM_by_day.parquet.csv" -o data/2025-11-14/wtc11-tfperturbseq-ref-avg-cpm-by-day.csv
    ```
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Constants""")
    return


@app.cell
def _():
    CORELIST = [
        "element_gene_pair_identifier_hg38",
        "pct_change_effect_size",
    #     "largest_singleton_pct_change_effect_size",
        "distance_to_gencode_gene_TSS",
        "direct_rate_negative",
        "element_category",
        "ubiq_category",
    #    "gencode_v44_coding_overlap",
        "gencode_protein_coding_gene_body_overlap"
    #    "overlapping_exon",
    #    "rmsk_nearby"
    ]
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Load Data""")
    return


@app.cell
def _(BedTool, Path, pd):
    tbl_s3 = pd.read_csv(
        "data/2025-11-14/dctapseq-tables3-wtc11.tsv", 
        sep="\t",
        dtype={
            "significant_wo_pos_controls_20fdr": str
        }
    )

    wtc11_singleton = pd.read_csv(
        "data/2025-11-14/wtc11-singleton.tsv",
        sep="\t",
        dtype={
            "significant": "boolean"
        }
    )

    wtc11_tfperturb = pd.read_csv(
        "data/2025-11-14/wtc11-tfperturbseq-ref-avg-cpm-by-day.csv"
    ).loc[:, ["gene_symbol", "D0"]]

    gtf = Path("data/2025-11-14/standardized/gencode.v44.annotation.gtf.gz")

    """
    For this analysis, repeatmasker bed files were obtained from
    Broad Institute's IGV public database. Find the referenced files at
    https://data.broadinstitute.org/igvdata/annotations/hg38/rmsk/{*.bed.gz}
    """
    rmsk_dict = {
        "DNA" : BedTool("data/2025-11-10/rmsk/DNA.bed.gz"),
        "LINE" : BedTool("data/2025-11-10/rmsk/LINE.bed.gz"),
        "LTR" : BedTool("data/2025-11-10/rmsk/LTR.bed.gz"),
        "RC" : BedTool("data/2025-11-10/rmsk/RC.bed.gz"),
        "Retroposon" : BedTool("data/2025-11-10/rmsk/Retroposon.bed.gz"),
        "RNA" : BedTool("data/2025-11-10/rmsk/RNA.bed.gz"),
        "rRNA" : BedTool("data/2025-11-10/rmsk/rRNA.bed.gz"),
        "Satellite" : BedTool("data/2025-11-10/rmsk/Satellite.bed.gz"),
        "scRNA" : BedTool("data/2025-11-10/rmsk/scRNA.bed.gz"),
        "Simplerepeats" : BedTool("data/2025-11-10/rmsk/Simple_repeat.bed.gz"),
        "SINE" : BedTool("data/2025-11-10/rmsk/SINE.bed.gz"),
        "snRNA" : BedTool("data/2025-11-10/rmsk/snRNA.bed.gz"),
        "srpRNA" : BedTool("data/2025-11-10/rmsk/srpRNA.bed.gz"),
        "tRNA" : BedTool("data/2025-11-10/rmsk/tRNA.bed.gz"),
        "UNKNOWN" : BedTool("data/2025-11-10/rmsk/UNKNOWN.bed.gz")
    }
    return rmsk_dict, tbl_s3, wtc11_singleton, wtc11_tfperturb


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Pre-processing Data""")
    return


@app.cell
def _(tbl_s3):
    def preprocess():
        df = tbl_s3.copy()

        # Filter for significant WTC11 E-G pairs. Include negative and positive % change effect sizes.
        df = df[
            (df["cell_type"].eq("WTC11")) &
            (df["significant_wo_pos_controls_20fdr"].eq("TRUE")) &
            (df["Random_DistalElement_Gene"].eq(True))
        ]

        return df
    return (preprocess,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Functions & Methods""")
    return


@app.cell
def _(BedTool, pd):
    # Function to make a bed file from pre-defined columns
    def mkbed(df):
        """
        Function to make a BedTool Object from from pre-defined columns.
        """
        df = df.copy()
        bed_df = pd.DataFrame({
            "chr": df.loc[:, "targeting_chr_hg38"],
            "start": df.loc[:, "targeting_start_hg38"] - 1, # Convert to 0-based
            "end": df.loc[:, "targeting_end_hg38"],
            "name": df.loc[:, "element_gene_pair_identifier_hg38"],
            "score": ".",
            "strand": "."
        })
        bed = BedTool.from_dataframe(bed_df)
        return bed
    return (mkbed,)


@app.cell
def _(mkbed, rmsk_dict):
    # A set of functions to overlap RepeatMasker features
    def overlap_rmsk(i, q, w = 350):
        """
        Helper method for overlapping RepeatMasker (rmsk) Features.
        Finds nearby rmsk features given an set of genomic coordinate 
        interval inputs and a single rmsk reference (e.g. SINE).

        Parameters
        ----------
        i : pybedtools BedTool Object Input
        q : pybedtools BedTool Object RepeatMasker reference query
        w : defines a nearby window around an interval.
            Default is 350 bp which defines a 1000-bp interval
            for most DC-TAP-seq tested elements. A 1000-bp
            interval for defining nearby rmsk features is an
            arbitrary definition.

        Returns
        -------
        A list of genomic coordiantes names overlapping a nearby rmsk 
        feature within a specified window.
        """
        nearby = i.slop(genome="hg38", l=w, r=w)
        intersect = nearby.intersect(q)
        return [interval.name for interval in intersect]

    def label_overlap(df, label, match_list):
        """
        Helper method for labeling intervals for an existing dataframe
        given a rmsk feature label and a match list.
        """
        label = "rmsk_" + label
        df.loc[df['element_gene_pair_identifier_hg38'].isin(match_list), label] = True
        df.loc[~df['element_gene_pair_identifier_hg38'].isin(match_list), label] = False
        return df

    def find_nearby_rmsk(df, rmsk = rmsk_dict):
        """
        Function to find nearby RepeatMasker (rmsk) Features and append 
        results to an existing pre-defined dataframe.

        Parameters
        ----------
        df : an existing dataframe to append rmsk annotations onto.
        rmsk : refers to repeatmasker definitions and or references.
        """
        df_results = df.copy()
        bed = mkbed(df_results)

        # Find all nearby repetitive genomic regions within a 350-bp window around the element interval 
        # For most cases the total window frame is 1000-bp.
        for k, v in rmsk.items():
            nearby = overlap_rmsk(bed, v)
            df_results = label_overlap(df_results, k, nearby)

        # Label Pair if there exists any nearby repetitive elements
        rmsk_cols = df_results.filter(regex="^rmsk_").columns
        df_results["rmsk_nearby"] = df_results[rmsk_cols].any(axis=1)

        return df_results
    return (find_nearby_rmsk,)


@app.cell
def _(pd):
    # A set of functions to add Singleton features
    def merge_singleton(df_s3, df_sing):
        """
        Helper method to merge singleton dataframe to table_s3 dataframe
        """
        # Split comma-separated guide_ids into lists
        df_s3["guide_list"] = df_s3["guide_ids"].str.split(",")

        # Explode to one row per guid
        df_s3_expanded = df_s3.explode("guide_list")
        df_s3_expanded["guide_list"] = df_s3_expanded["guide_list"].str.strip()

        # Merge with df_sing to get effect_size for each guide
        merged = df_s3_expanded.merge(
            df_sing[[
                "grna_id", 
                "response_id", 
                "pct_change_effect_size",
                "n_nonzero_trt",
                "n_nonzero_cntrl",
                "standard_error_pct_change"
            ]],
            left_on=["guide_list", "gene_id"],
            right_on=["grna_id", "response_id"],
            how="left",
        )

        # Re-label column names
        merged = merged.rename(columns={
            "response_id" : "singleton_response_id",
            "pct_change_effect_size_x" : "pct_change_effect_size", # fix original colname
            "pct_change_effect_size_y" : "singleton_pct_change_effect_size",
            "n_nonzero_trt" : "singleton_n_nonzero_trt",
            "n_nonzero_cntrl" : "singleton_n_nonzero_cntrl",
            "standard_error_pct_change_x" : "standard_error_pct_change", # fix original colname
            "standard_error_pct_change_y" : "singleton_standard_error_pct_change"
        })
    
        return merged

    def get_nth_performing_guide(df_merged, n, is_negative_direction):
        """
        Helper method to fetch n-th best performing guide with respect to
        direction of effect.
        """
        df_merged = df_merged.copy()
        is_ascending = True

        if is_negative_direction:
            df_merged = df_merged.loc[df_merged["pct_change_effect_size"] < 0 ]
        else:
            df_merged = df_merged.loc[df_merged["pct_change_effect_size"] > 0 ]
            is_ascending = False
    
        # Pre-process merged df. Sorts guides by singleton % change effect size
        df_nth_guide_features = (
            df_merged
                .sort_values(
                    [
                        "element_gene_pair_identifier_hg38",
                        "singleton_pct_change_effect_size"
                    ],
                    ascending = is_ascending
                ).groupby("element_gene_pair_identifier_hg38")[[
                    "element_gene_pair_identifier_hg38",
                    "grna_id",
                    "singleton_n_nonzero_trt",
                    "singleton_n_nonzero_cntrl",
                    "singleton_pct_change_effect_size",
                    "singleton_standard_error_pct_change"
                ]].head(n)
        )
    
        return df_nth_guide_features

    def format_merged_singleton_guides(df_results, df_ref, n):
        """
        Helper method to format and append statistics and feature columns of the n-th best
        performing guide.
        """
        l = f"singleton_g{n + 1}"               # label
        m = "element_gene_pair_identifier_hg38" # mapper
        df_ref = df_ref.copy().groupby(m).nth(n).set_index(m)

        df_results[f"{l}_guide_id"] = df_results[m].map(df_ref["grna_id"])
        df_results[f"{l}_counts_trt"] = df_results[m].map(df_ref["singleton_n_nonzero_trt"])
        df_results[f"{l}_counts_ctl"] = df_results[m].map(df_ref["singleton_n_nonzero_cntrl"])
        df_results[f"{l}_pctchange_effect_size"] = df_results[m].map(df_ref["singleton_pct_change_effect_size"].round(2))
        df_results[f"{l}_pctchange_stderror"] = df_results[m].map(df_ref["singleton_standard_error_pct_change"].round(2))
        df_results[f"{l}_pctchange_ci_interval"] = df_results[m].map(
            round(df_ref["singleton_standard_error_pct_change"] * 1.96, 2)
        )

    def format_merged_singleton_guides_summary_columns(df_results):
        """
        Helper method to format singleton guide stats in a single summary column.
        """
        sl = f"summary_singleton" # summary label

        # Select singleton columns
        cols = [c for c in df_results.columns if c.startswith("singleton_g")]

        # Group columns
        groups = {}
        for c in cols:
            stats = c.split("_", 2)[-1]
            groups.setdefault(stats, []).append(c)

        # Build summary columns
        for stats, cols in groups.items():
            summary_col = f"{sl}_{stats}"
            df_results[summary_col] = df_results[cols].astype(str).agg(", ".join, axis=1)

    def get_singletonfeatures(df, df_singleton, n = 3):
        """
        Function to get singleton features for each E-G pair.
        Features to get are the top 3 best performing guide 
        (by % change effect size and direction of effect) and 
        their associated statistics.

        Singleton results referenced was analyzed using SCEPTRE tool.
        See DC-TAP-seq Github for details.

        Statistics/Feature Column
        -------------------------
        singleton_*_guide_id : The guide id of the n-th best performing guide.
        singleton_*_guides : The total number of unique guide designed against a tested element. (NOT IMPLEMENTED)
        singleton_*_counts_trt : The total number of nonzero treatment. (N cells where guide was detected)
        singleton_*_counts_ctl : The total number of control treatment. (N cells where guide was not detected)
        singleton_*_pctchange_effect_size : The percentage change effect size of the indicated single guide.
        singleton_*_pctchange_stderror : The percentage change effect size standard error statistics of the 
                                         indicated single guide.
        singleton_*_pctchange_ci_interval : The percentage change effect size 95% confidence interval difference 
                                            of the indicated single guide. (ci_interval = +/- 1.96 * stderr)
                                        
        Note
        ----
        * denotes n-th best performing guide. For example, "g1" is the best performing and 
          "g3" is 3rd best performing guide.
    
        Parameters
        ----------
        df : an existing dataframe to append singleton features onto.
        df_singleton : refers to DC-TAP-seq singleton guide differential expression analysis dataframe via SCEPTRE tool.
        n : the n-th best performing singleton guide feature to fetch.

        Returns
        -------
        Append results to an existing pre-defined dataframe.
        """
        df = df.copy()

        # Merge Singleton annotations to Table_S3
        df_merged = merge_singleton(df, df_singleton)
    
        # Get the n-th best performing guide for when direction of effect is neg/pos
        df_nth_feat_neg = get_nth_performing_guide(df_merged, n, is_negative_direction=True)
        df_nth_feat_pos = get_nth_performing_guide(df_merged, n, is_negative_direction=False)

        # Concat both direction of effect guide features
        df_nth_performing_guides = pd.concat([df_nth_feat_neg, df_nth_feat_pos])

        # For each n-th guide, format and append singleton features to results dataframe
        for i in range(n):
            format_merged_singleton_guides(df, df_nth_performing_guides, i)
        format_merged_singleton_guides_summary_columns(df)
    
        return df
    return (get_singletonfeatures,)


@app.cell
def _(BedTool, Path, mkbed, subprocess):
    # A set of functions to get overlapping exons from GENCODE v44 
    def get_wtc11_exon_overlaps(df, gtf):
        """
        Work in progress.
        """
        df = df.copy()
        file = Path(gtf.stem).stem
        path = Path(f"{gtf.parent}/{file}.exon.bed")
        m = "element_gene_pair_identifier_hg38" # mapper
        o = "gencode_v44_exon_overlaps"         # overlaps
    
        # Filter GTF for exons and make BedTool object
        if not path.exists():
            exon_bed = subprocess.check_output(
                ["bash", "src/bash/gtf_to_exonbed.sh", gtf], text=True
            ).strip()
            exon = BedTool(exon_bed)
        exon = BedTool(path)

        # Make BedTool object of query
        q = mkbed(df)

        # Find overlapping exons
        overlaps = q.intersect(exon, wa=True, wb=True)

        # Format
        overlaps = overlaps.to_dataframe(header=None, usecols=[3, 9])
        overlaps = overlaps.rename(columns={3: m, 9: o})
        overlaps = overlaps.drop_duplicates(subset=[m, o])
    
        # Aggregate multiple exon overlaps per pair
        agg = (
            overlaps
            .groupby(m)[o]
            .apply(lambda s: ",".join(s.astype(str)))
        )

        # Map to Table S3
        df[o] = df[m].map(agg)
    
        return df

    def get_wtc11_simple_exon_overlaps(df):
        """
        Placeholder for exon overlaps
        """
        df = df.copy()
        m = "gencode_protein_coding_gene_body_overlap" # mapper
        o = "overlapping_exon"                         # output result
    
        df[o] = df[m].notna()
        return df

    return (get_wtc11_simple_exon_overlaps,)


@app.cell
def _(get_wtc11_simple_exon_overlaps):
    # A set of functions to add relevant WTC11 Gene CPM to Pairs with overlapping exons
    def get_wtc11_gene_expression(df, df_ref, threshold = 10):
        """
        Function to get reference WTC11 scRNA-seq gene expression dataset
        from previous studies (2022-06-25 TF-Perturb-seq WTC11 by Jones Group 
        from the Lander Lab at the Broad Institute) onto DC-TAP-seq Table S3.

        Parameters
        ----------
        df : an existing dataframe to append scRNA-seq data onto.
        df_ref : refers to a previous study scRNA-seq dataset of a similar cell-line.
        """
        df = df.copy()
        p = "element_gene_pair_identifier_hg38"        # e-g pairs
        m = "gencode_protein_coding_gene_body_overlap" # mapper
        o = "overlapping_exon"                         # overlaps

        # df_ref columns
        g = "gene_symbol"
        r = "overlapping_exon_cpm"
        d = "D0"

        # Get exon overlaps
        df = get_wtc11_simple_exon_overlaps(df)
    
        # Filter for pairs with overlapping exon
        overlaps = df.loc[:, [p,m,o]]
        overlaps = overlaps.loc[df[o] == True]

        # Aggregate multiple exon overlaps per pair
        agg = (
            df_ref
            .groupby(g)[d]
            .apply(lambda s: ",".join(s.astype(str)))
        )

        # Map to Table S3
        df[r] = overlaps[m].map(agg)
        df["overlapping_exon_is_lowly_expressed"] = df[r].astype(float) < threshold
    
        return df
    return (get_wtc11_gene_expression,)


@app.cell
def _(
    find_nearby_rmsk,
    get_singletonfeatures,
    get_wtc11_gene_expression,
    rmsk_dict,
    wtc11_singleton,
    wtc11_tfperturb,
):
    # Process
    def process(df):
        CORELIST = [
            "element_gene_pair_identifier_hg38",
            "pct_change_effect_size",
            "distance_to_gencode_gene_TSS",
            "element_category",
            "ubiq_category",
            "gencode_protein_coding_gene_body_overlap",
            "overlapping_exon",
            "overlapping_exon_cpm",
            "overlapping_exon_is_lowly_expressed",
            "rmsk_nearby",
            "direct_vs_indirect_negative"
        ]

        # Get Repeatmasker Overlaps
        df = find_nearby_rmsk(df, rmsk_dict)

        # Get singleton features
        df = get_singletonfeatures(df, wtc11_singleton)
        # Select summary singleton columns
        singleton = [c for c in df.columns if c.startswith("summary_singleton")]
        CORELIST.extend(singleton)

        # Get overlapping exons and gene expression levels
        df = get_wtc11_gene_expression(df, wtc11_tfperturb)

        # Format return full df and core df
        return df, df.loc[:, CORELIST]
    
    return (process,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Run Scripts & Functions""")
    return


@app.cell
def _(preprocess, process):
    tbl_s3_preprocessed = preprocess()
    tbl_s3_processed, tbl_s3_processed_summary = process(tbl_s3_preprocessed)
    return (tbl_s3_processed_summary,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Exploration""")
    return


@app.cell
def _(mo, tbl_s3_processed_summary):
    # Show all 99 sig pairs.
    mo.ui.dataframe(tbl_s3_processed_summary)
    return


@app.cell
def _(mo, tbl_s3_processed_summary):
    # Filtering for CTCF element category and look at largest magnitude % pct change eff. size
    mo.ui.dataframe(
        tbl_s3_processed_summary[
            (tbl_s3_processed_summary["pct_change_effect_size"] > 10) |
            (tbl_s3_processed_summary["pct_change_effect_size"] < -10)
        ]
    )
    return


@app.cell
def _(mo, tbl_s3_processed_summary):
    # Filter for the best validation targets
    mo.ui.dataframe(
        tbl_s3_processed_summary[
            (tbl_s3_processed_summary["pct_change_effect_size"] < -10) & 
            (tbl_s3_processed_summary["distance_to_gencode_gene_TSS"] < 100000) & 
            (tbl_s3_processed_summary["overlapping_exon"] == False)
        ]
    )
    return


@app.cell
def _(mo, tbl_s3_processed_summary):
    # This list is for low-MOI vs high-MOI DC-TAP-seq validation experiment
    mo.ui.dataframe(
        tbl_s3_processed_summary[
            # All elements curated is less than 100kb
            # The 4 element below were choosen because >abs(10) % change effect, no overlapping exon, <100kb
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "PCBP1|chr2:70089449-70089750") | 
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "HMGA1|chr6:34235537-34235838") | 
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "FAM111A|chr11:59158502-59158803") | 
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "CEBPB|chr20:50192829-50193130") | 

            # The 2 elements below were choosen because >abs(10) % change effect, 
            # overlapped exon is lowly expressed and <100kb
            # MFSD3 is no K27ac marked (weak target for validation, could be removed if needed)
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "MFSD3|chr8:144511963-144512264") |
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "FOXH1|chr8:144472391-144472692") | 

            # Direction of effect is negative
            # SLC2A3 & TP53 locus plot were highlighted in the paper 
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "SLC2A3|chr12:7960676-7960977") | 
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "TP53|chr17:7656987-7657288") |

            # Direction of effect is negative
            # CFL1, overlapped exon is lowly expressed, K27me3 marked
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "CFL1|chr11:65355795-65356096") |

            # Direction of effect is negative
            # CTCF element
            # CFL1, overlapped exon is lowly expressed
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "CDC37|chr19:10390714-10391015") |
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "RPL8|chr8:144805052-144805353") |

            # Direction of effect is negative, overlapped exon is lowly expressed, no K27ac marked
            (tbl_s3_processed_summary["element_gene_pair_identifier_hg38"] == "PIMREG|chr17:6455432-6455733")
        ]
    )
    return


if __name__ == "__main__":
    app.run()
